spring:
  application:
    name: task-service
    config:
      import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084
  servlet:
    context-path: /task/

eureka:
  client:
    service-url:
      defaultZone: http://20.11.21.61:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  default-produces-media-type: application/json
  api-docs: # Add this section
    path: /v3/api-docs
  swagger-ui: # Add this section
    path: /swagger-ui.html

# Custom path for uploaded files

