server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/task/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/**
        - id: candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/**

        - id: task-service-api-docs
          uri: lb://task-service
          predicates:
            - Path=/task/v3/api-docs/**
          filters:
            - RewritePath=/task/(?<path>.*), /${path}

        - id: task-service-openapi
          uri: lb://task-service
          predicates:
            - Path=/task/swagger-ui.html
          filters:
            - RewritePath=/task/(?<path>.*), /${path}

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: student-service-api-docs
          uri: lb://student-service
          predicates:
            - Path=/student/v3/api-docs/**
          filters:
            - RewritePath=/student/(?<path>.*), /${path}

        - id: student-service-openapi
          uri: lb://student-service
          predicates:
            - Path=/student/swagger-ui.html
          filters:
            - RewritePath=/student/(?<path>.*), /${path}

        - id: user-service
          uri: lb:http://user-service
          predicates:
            - Path=/api/v1/**

        - id: user-service-openapi
          uri: lb://user-service
          predicates:
            - Path=/api/v1/swagger-ui.html
          filters:
            - RewritePath=/api/v1/(?<path>.*), /${path}

        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/api/v1/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/(?<path>.*), /${path}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: notification-service-api-docs
          uri: lb://notification-service
          predicates:
            - Path=/notifications/v3/api-docs/**
          filters:
            - RewritePath=/notifications/(?<path>.*), /${path}

        - id: notification-service-openapi
          uri: lb://notification-service
          predicates:
            - Path=/notifications/swagger-ui.html
          filters:
            - RewritePath=/notifications/(?<path>.*), /${path}

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/**

        # Route for event-service Swagger UI
        - id: event-service-openapi
          uri: lb://event-service
          predicates:
            - Path=/events/swagger-ui.html
          filters:
            - RewritePath=/events/(?<path>.*), /${path}

        # Route for event-service API Docs
        - id: event-service-api-docs
          uri: lb://event-service
          predicates:
            - Path=/events/v3/api-docs/**
          filters:
            - RewritePath=/events/(?<path>.*), /${path}


        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /${path}/v3/api-docs

    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "http://localhost:4200"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders: "*"
          allowCredentials: true

springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /task/v3/api-docs
        name: Task Service
      - url: /student/v3/api-docs
        name: Student Service
      - url: /api/v1/v3/api-docs
        name: User Service
      - url: /notifications/v3/api-docs
        name: Notification Service
      - url: /events/v3/api-docs
        name: Event Service
    path: /swagger-ui.html
