spring:
  application:
    name: student-service
    config:
      import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:mysql://localhost:3306/candidate?maxAllowedPacket=16777216
    username: user
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8082
  servlet:
    context-path: /student/

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

