spring:
  application:
    name: user-service


  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  # File storage properties
  file:
    upload-dir: src/main/resources/static/images # Directory to save uploaded files

springdoc:
  default-produces-media-type: application/json
  api-docs: # Add this section
    path: /v3/api-docs
  swagger-ui: # Add this section
    path: /swagger-ui.html

server:
  servlet:
    context-path: /api/v1/