server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: http://20.11.21.61
    prefer-ip-address: true
    ip-address: http://20.11.21.61
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://20.11.21.61:${server.port}/eureka/
  server:
    enableSelfPreservation: false
